- src: git@github.com:netology-code/mnt-homeworks-ansible.git
  scm: git
  version: "1.0.1"
  name: java
- src: git@github.com:Kapelman/elastic-role.git
  scm: git
  name: elastic_role
- src: git@github.com:Kapelman/kibana-role.git
  scm: git
  name: kibana_role
